// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// center
NumericMatrix center(NumericMatrix M, NumericVector w, int N);
RcppExport SEXP _semiaftosmac_center(SEXP MSEXP, SEXP wSEXP, SEXP NSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type M(MSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type w(wSEXP);
    Rcpp::traits::input_parameter< int >::type N(NSEXP);
    rcpp_result_gen = Rcpp::wrap(center(M, w, N));
    return rcpp_result_gen;
END_RCPP
}
// km
List km(NumericVector e, NumericVector d, NumericVector p);
RcppExport SEXP _semiaftosmac_km(SEXP eSEXP, SEXP dSEXP, SEXP pSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type e(eSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type d(dSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type p(pSEXP);
    rcpp_result_gen = Rcpp::wrap(km(e, d, p));
    return rcpp_result_gen;
END_RCPP
}
// gehan_smth
arma::mat gehan_smth(arma::mat x, arma::vec y, arma::uvec d, arma::vec beta, arma::vec p, int n);
RcppExport SEXP _semiaftosmac_gehan_smth(SEXP xSEXP, SEXP ySEXP, SEXP dSEXP, SEXP betaSEXP, SEXP pSEXP, SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type x(xSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type y(ySEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type d(dSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type p(pSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(gehan_smth(x, y, d, beta, p, n));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_semiaftosmac_center", (DL_FUNC) &_semiaftosmac_center, 3},
    {"_semiaftosmac_km", (DL_FUNC) &_semiaftosmac_km, 3},
    {"_semiaftosmac_gehan_smth", (DL_FUNC) &_semiaftosmac_gehan_smth, 6},
    {NULL, NULL, 0}
};

RcppExport void R_init_semiaftosmac(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
